version: '3.8'
services:
  react-app:
    build: .
    ports:
      - "80:80"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - NODE_ENV=production
      - NTFY_TOKEN=$NTFY_TOKEN
      - NTFY_URL=$NTFY_URL
    restart: unless-stopped