version: '3.8'
services:
  react-app:
    build: .
    ports:
      - "80:80"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - NODE_ENV=production
    restart: unless-stopped