version: '3.8'
services:
  react-app:
    build: .
    ports:
      - "82:80"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - NODE_ENV=production
      - REACT_APP_NTFY_TOKEN=$REACT_APP_NTFY_TOKEN
      - REACT_APP_NTFY_URL=$REACT_APP_NTFY_URL
    restart: unless-stopped
